# ASP.NET Core
 

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
container:
- task: nuget-security-analysis@0
- task: CredScan@3
  displayName: Credential Scanning
  inputs:
    enabled: true
- task: UseDotNet@2
  displayName: Use DotNet 5.0
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: DotNetCoreCLI@2
  displayName: Restoring dependencies
  inputs:
    command: restore
    projects: '**/src/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/src/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/Test.UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

